// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/stream_ingest.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamIngestService_StartStream_FullMethodName = "/stream.StreamIngestService/StartStream"
	StreamIngestService_StopStream_FullMethodName  = "/stream.StreamIngestService/StopStream"
)

// StreamIngestServiceClient is the client API for StreamIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Stream Ingest gRPC service definition
type StreamIngestServiceClient interface {
	StartStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamResponse, error)
	StopStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamResponse, error)
}

type streamIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamIngestServiceClient(cc grpc.ClientConnInterface) StreamIngestServiceClient {
	return &streamIngestServiceClient{cc}
}

func (c *streamIngestServiceClient) StartStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamResponse)
	err := c.cc.Invoke(ctx, StreamIngestService_StartStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamIngestServiceClient) StopStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (*StreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamResponse)
	err := c.cc.Invoke(ctx, StreamIngestService_StopStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamIngestServiceServer is the server API for StreamIngestService service.
// All implementations must embed UnimplementedStreamIngestServiceServer
// for forward compatibility.
//
// Stream Ingest gRPC service definition
type StreamIngestServiceServer interface {
	StartStream(context.Context, *StreamRequest) (*StreamResponse, error)
	StopStream(context.Context, *StreamRequest) (*StreamResponse, error)
	mustEmbedUnimplementedStreamIngestServiceServer()
}

// UnimplementedStreamIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamIngestServiceServer struct{}

func (UnimplementedStreamIngestServiceServer) StartStream(context.Context, *StreamRequest) (*StreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartStream not implemented")
}
func (UnimplementedStreamIngestServiceServer) StopStream(context.Context, *StreamRequest) (*StreamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopStream not implemented")
}
func (UnimplementedStreamIngestServiceServer) mustEmbedUnimplementedStreamIngestServiceServer() {}
func (UnimplementedStreamIngestServiceServer) testEmbeddedByValue()                             {}

// UnsafeStreamIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamIngestServiceServer will
// result in compilation errors.
type UnsafeStreamIngestServiceServer interface {
	mustEmbedUnimplementedStreamIngestServiceServer()
}

func RegisterStreamIngestServiceServer(s grpc.ServiceRegistrar, srv StreamIngestServiceServer) {
	// If the following call pancis, it indicates UnimplementedStreamIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamIngestService_ServiceDesc, srv)
}

func _StreamIngestService_StartStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamIngestServiceServer).StartStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamIngestService_StartStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamIngestServiceServer).StartStream(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamIngestService_StopStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamIngestServiceServer).StopStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamIngestService_StopStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamIngestServiceServer).StopStream(ctx, req.(*StreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamIngestService_ServiceDesc is the grpc.ServiceDesc for StreamIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamIngestService",
	HandlerType: (*StreamIngestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartStream",
			Handler:    _StreamIngestService_StartStream_Handler,
		},
		{
			MethodName: "StopStream",
			Handler:    _StreamIngestService_StopStream_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stream_ingest.proto",
}
