// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.0
// source: proto/stream_processing.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamProcessingService_StartProcessing_FullMethodName = "/stream.StreamProcessingService/StartProcessing"
)

// StreamProcessingServiceClient is the client API for StreamProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Stream Processing gRPC service definition
type StreamProcessingServiceClient interface {
	StartProcessing(ctx context.Context, in *ProcessingRequest, opts ...grpc.CallOption) (*ProcessingResponse, error)
}

type streamProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamProcessingServiceClient(cc grpc.ClientConnInterface) StreamProcessingServiceClient {
	return &streamProcessingServiceClient{cc}
}

func (c *streamProcessingServiceClient) StartProcessing(ctx context.Context, in *ProcessingRequest, opts ...grpc.CallOption) (*ProcessingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessingResponse)
	err := c.cc.Invoke(ctx, StreamProcessingService_StartProcessing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StreamProcessingServiceServer is the server API for StreamProcessingService service.
// All implementations must embed UnimplementedStreamProcessingServiceServer
// for forward compatibility.
//
// Stream Processing gRPC service definition
type StreamProcessingServiceServer interface {
	StartProcessing(context.Context, *ProcessingRequest) (*ProcessingResponse, error)
	mustEmbedUnimplementedStreamProcessingServiceServer()
}

// UnimplementedStreamProcessingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamProcessingServiceServer struct{}

func (UnimplementedStreamProcessingServiceServer) StartProcessing(context.Context, *ProcessingRequest) (*ProcessingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartProcessing not implemented")
}
func (UnimplementedStreamProcessingServiceServer) mustEmbedUnimplementedStreamProcessingServiceServer() {
}
func (UnimplementedStreamProcessingServiceServer) testEmbeddedByValue() {}

// UnsafeStreamProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamProcessingServiceServer will
// result in compilation errors.
type UnsafeStreamProcessingServiceServer interface {
	mustEmbedUnimplementedStreamProcessingServiceServer()
}

func RegisterStreamProcessingServiceServer(s grpc.ServiceRegistrar, srv StreamProcessingServiceServer) {
	// If the following call pancis, it indicates UnimplementedStreamProcessingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamProcessingService_ServiceDesc, srv)
}

func _StreamProcessingService_StartProcessing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamProcessingServiceServer).StartProcessing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamProcessingService_StartProcessing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamProcessingServiceServer).StartProcessing(ctx, req.(*ProcessingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StreamProcessingService_ServiceDesc is the grpc.ServiceDesc for StreamProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamProcessingService",
	HandlerType: (*StreamProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartProcessing",
			Handler:    _StreamProcessingService_StartProcessing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stream_processing.proto",
}
